# Generated by Django 4.1.1 on 2022-10-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='bell_duration',
            field=models.DurationField(max_length=2),
        ),
    ]
